---
- name: Clone nvm
  git: repo=git://github.com/creationix/nvm.git
       dest=~/.nvm
       version=v0.33.2

- name: Source nvm in ~/.zshrc
  lineinfile:
    path: ~/.zshrc
    line: "source ~/.nvm/nvm.sh"

- name: install node lts
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts"
