---
- name: Copy php
  copy:
    src: php
    dest: /usr/local/bin/php
    mode: a+x
  register: php
  become: yes

- name: Copy phpunit
  copy:
    src: phpunit
    dest: /usr/local/bin/phpunit
    mode: a+x
  register: phpunit
  become: yes

- name: Copy composer
  copy:
    src: composer
    dest: /usr/local/bin/composer
    mode: a+x
  register: composer
  become: yes

- name: Copy phpcs
  copy:
    src: phpcs
    dest: /usr/local/bin/phpcs
    mode: a+x
  register: phpcs
  become: yes

- name: Copy phpcbf
  copy:
    src: phpcbf
    dest: /usr/local/bin/phpcbf
    mode: a+x
  register: phpcbf
  become: yes
