---
- name: Install epel repo
  yum: name=epel-release state=latest
  become: yes

- name: Install ius repo
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=latest
  become: yes

- name: Install git 2
  yum: name=git2u state=latest
  become: yes

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig

- name: Copy .gitignore
  copy:
    src: .gitignore
    dest: ~/.gitignore

- name: Copy .git-commit-template.txt
  copy:
    src: .git-commit-template.txt
    dest: ~/.git-commit-template.txt
